// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3feCu0xiIBkApD_ue30KqKxf6Lc7WRA0',
    appId: '1:265455404120:web:738b0a8eb2fa655539362d',
    messagingSenderId: '265455404120',
    projectId: 'free-talk-cca8f',
    authDomain: 'free-talk-cca8f.firebaseapp.com',
    storageBucket: 'free-talk-cca8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdKaL7x1WJk16JSbCfeJEaN_gMHnCvN4A',
    appId: '1:265455404120:android:49aa74d86d1e247c39362d',
    messagingSenderId: '265455404120',
    projectId: 'free-talk-cca8f',
    storageBucket: 'free-talk-cca8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmffkgYerWX59EOyA6_Yx9WO8w9MQhEfA',
    appId: '1:265455404120:ios:eddded369c395ba539362d',
    messagingSenderId: '265455404120',
    projectId: 'free-talk-cca8f',
    storageBucket: 'free-talk-cca8f.appspot.com',
    iosBundleId: 'com.example.freeTalk',
  );
}
